name: Check MDX Heading Changes

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'nextjs/src/app/kb/_content/**/*.mdx'

jobs:
  check-mdx-headings:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install @octokit/rest

      - name: Run MDX heading check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .github/scripts/check_mdx_headings.js
